# Generated by Django 6.0 on 2026-08-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_alter_character_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('classified', 'Clasificado'), ('deleted', 'Eliminado')], default='active', max_length=16),
        ),
    ]
