# Generated by Django 6.0 on 2026-08-24 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_character_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='faction',
            field=models.CharField(blank=True, default='', max_length=32, validators=[django.core.validators.MaxLengthValidator(64)]),
        ),
    ]
