# Generated by Django 6.0 on 2026-08-25 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_character_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='photo_url',
            field=models.URLField(blank=True, default='', help_text='Enlace directo a la imagen (Discord, imgur, etc.)', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
