# Generated by Django 6.0 on 2026-08-24 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_booster',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UsernameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_username', models.CharField(max_length=100)),
                ('new_username', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Username',
                'verbose_name_plural': 'Historial de Usernames',
                'ordering': ['-changed_at'],
            },
        ),
    ]
