# Generated by Django 6.0.3 on 2026-03-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('factions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='factions.faction'),
        ),
    ]
