# Generated by Django 6.0 on 2026-08-24 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ssutogglelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('rp', 'In-RP'), ('technical', 'Técnico')], default='rp', max_length=16)),
                ('access_level', models.CharField(default='L1', max_length=4)),
                ('query', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('used_llm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta AI',
                'verbose_name_plural': 'Consultas AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
