# Generated by Django 6.0.3 on 2026-03-15 15:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0006_alter_character_faction'),
        ('factions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('doc_type', models.CharField(choices=[('procedure', 'Procedimiento'), ('memo', 'Memo'), ('briefing', 'Briefing'), ('regulation', 'Reglamento'), ('other', 'Otro')], default='other', max_length=20)),
                ('content', models.TextField(validators=[django.core.validators.MaxLengthValidator(100000)])),
                ('min_access_level', models.CharField(default='L1', max_length=10)),
                ('author_faction', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_authored', to=settings.AUTH_USER_MODEL)),
                ('restricted_faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='factions.faction')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_content', models.TextField(blank=True)),
                ('new_content', models.TextField()),
                ('edit_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='scps.document')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Edición de Documento',
                'verbose_name_plural': 'Logs de Edición de Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scp_id', models.CharField(help_text='ej: SCP-2995', max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('object_class', models.CharField(choices=[('safe', 'Safe'), ('euclid', 'Euclid'), ('keter', 'Keter'), ('thaumiel', 'Thaumiel'), ('neutralized', 'Neutralized'), ('apollyon', 'Apollyon'), ('archon', 'Archon')], default='euclid', max_length=20)),
                ('content_l1', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(50000)])),
                ('content_l2', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(50000)])),
                ('content_l3', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(50000)])),
                ('content_l4', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(50000)])),
                ('content_l5', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(50000)])),
                ('content_l6', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(50000)])),
                ('appendices', models.JSONField(default=list, help_text='Lista de apéndices con nivel y contenido')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_character', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scp_file', to='characters.character')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scps_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo SCP',
                'verbose_name_plural': 'Archivos SCP',
                'ordering': ['scp_id'],
            },
        ),
        migrations.CreateModel(
            name='SCPEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(help_text='L1, L2, etc. o appendix', max_length=20)),
                ('old_content', models.TextField(blank=True)),
                ('new_content', models.TextField()),
                ('edit_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scp_edits', to=settings.AUTH_USER_MODEL)),
                ('scp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='scps.scp')),
            ],
            options={
                'verbose_name': 'Log de Edición SCP',
                'verbose_name_plural': 'Logs de Edición SCP',
                'ordering': ['-created_at'],
            },
        ),
    ]
