# Generated by Django 6.0 on 2026-08-27 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_character_photo_url'),
        ('scps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SCPActorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Actor asignado'), ('unassigned', 'Actor removido'), ('file_edited', 'Archivo editado por el actor'), ('appendix_added', 'Apéndice agregado por el actor'), ('rp_action', 'Acción de roleplay registrada')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scp_actor_logs', to='characters.character')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scp_actor_actions', to=settings.AUTH_USER_MODEL)),
                ('scp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_logs', to='scps.scp')),
            ],
            options={
                'verbose_name': 'Log de Actor SCP',
                'verbose_name_plural': 'Logs de Actores SCP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scp', '-created_at'], name='scps_scpact_scp_id_5831fb_idx')],
            },
        ),
    ]
