# Generated by Django 6.0.3 on 2026-03-15 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0006_alter_character_faction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('L1', 'Nivel 1 - Básico'), ('L2', 'Nivel 2 - Standard'), ('L3', 'Nivel 3 - Intermedio'), ('L4', 'Nivel 4 - Alto'), ('L5', 'Nivel 5 - Máximo Secreto'), ('L6', 'Nivel 6 - O5 / Admin')], max_length=10, unique=True)),
                ('card_type', models.CharField(choices=[('standard', 'Estándar'), ('ethics_committee', 'Comité de Ética'), ('o5_council', 'Consejo O5'), ('raisa', 'RAISA'), ('admin_office', 'Oficina Administrativa'), ('beta_1', 'Beta-1')], default='standard', max_length=30)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('can_view_l1', models.BooleanField(default=True)),
                ('can_view_l2', models.BooleanField(default=False)),
                ('can_view_l3', models.BooleanField(default=False)),
                ('can_view_l4', models.BooleanField(default=False)),
                ('can_view_l5', models.BooleanField(default=False)),
                ('can_view_l6', models.BooleanField(default=False)),
                ('can_edit_scp', models.BooleanField(default=False)),
                ('can_edit_scd', models.BooleanField(default=False)),
                ('can_edit_o5', models.BooleanField(default=False)),
                ('can_edit_any', models.BooleanField(default=False)),
                ('is_classified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Nombre visible para usuarios normales', max_length=100)),
                ('faction_type', models.CharField(choices=[('department', 'Departamento'), ('council', 'Consejo'), ('special_force', 'Fuerza Especial'), ('classified', 'Clasificada')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('dissolved', 'Disuelta'), ('restricted', 'Restringida')], default='active', max_length=20)),
                ('is_classified', models.BooleanField(default=False)),
                ('facade_name', models.CharField(blank=True, help_text='Nombre visible代替 real', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#1a1a2e', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leaders', models.ManyToManyField(blank=True, related_name='led_factions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facción',
                'verbose_name_plural': 'Facciones',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='FactionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Mensaje del solicitante')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_applications', to='characters.character')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='factions.faction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Ingreso',
                'verbose_name_plural': 'Solicitudes de Ingreso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('member_joined', 'Miembro se unió'), ('member_left', 'Miembro salió'), ('rank_changed', 'Rango cambiado'), ('member_expelled', 'Miembro expulsado'), ('application_accepted', 'Solicitud aceptada'), ('application_rejected', 'Solicitud rechazada'), ('faction_created', 'Facción creada'), ('faction_disolved', 'Facción disuelta')], max_length=30)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faction_logs', to='characters.character')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='factions.faction')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faction_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Facción',
                'verbose_name_plural': 'Logs de Facciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactionRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='Nivel jerárquico (1=más bajo)')),
                ('can_manage_members', models.BooleanField(default=False)),
                ('can_review_applications', models.BooleanField(default=False)),
                ('can_assign_ranks', models.BooleanField(default=False)),
                ('access_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faction_ranks', to='factions.accesscard')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='factions.faction')),
            ],
            options={
                'verbose_name': 'Rango de Facción',
                'verbose_name_plural': 'Rangos de Facción',
                'ordering': ['faction', '-level'],
                'unique_together': {('faction', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CharacterFactionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('classified', 'Clasificado')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('access_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factions.accesscard')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_memberships', to='characters.character')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='factions.faction')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factions.factionrank')),
            ],
            options={
                'verbose_name': 'Membresía de Personaje',
                'verbose_name_plural': 'Membresías de Personajes',
                'unique_together': {('character', 'faction')},
            },
        ),
    ]
