# Generated by Django 6.0.3 on 2026-03-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscard',
            name='level',
            field=models.CharField(choices=[('L1', 'Nivel 1 - Básico'), ('L2', 'Nivel 2 - Standard'), ('L3', 'Nivel 3 - Intermedio'), ('L4', 'Nivel 4 - Alto'), ('L5', 'Nivel 5 - Máximo Secreto'), ('L6', 'Nivel 6 - O5 / Admin')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='accesscard',
            unique_together={('level', 'card_type')},
        ),
    ]
