# Generated by Django 6.0 on 2026-03-15 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_alter_character_faction'),
        ('factions', '0002_alter_accesscard_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='allow_applications',
            field=models.BooleanField(default=True, help_text='Permitir solicitudes de ingreso públicas'),
        ),
        migrations.AddField(
            model_name='faction',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Si es False, solo admins y miembros pueden ver la facción'),
        ),
        migrations.CreateModel(
            name='FactionInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('declined', 'Rechazada'), ('expired', 'Expirada')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_invitations', to='characters.character')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='factions.faction')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitación de Facción',
                'verbose_name_plural': 'Invitaciones de Facciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
