# Generated by Django 6.0 on 2026-03-15 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0003_faction_allow_applications_faction_is_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactionDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('access_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faction_divisions', to='factions.accesscard')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='factions.faction')),
            ],
            options={
                'verbose_name': 'División de Facción',
                'verbose_name_plural': 'Divisiones de Facción',
                'ordering': ['name'],
                'unique_together': {('faction', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FactionDivisionRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='factions.factiondivision')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('division', 'name')},
            },
        ),
    ]
