# Generated by Django 6.0 on 2026-03-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_alter_character_faction'),
        ('factions', '0004_factiondivision_factiondivisionrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='factiondivision',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Si es False, solo líderes pueden ver la división'),
        ),
        migrations.AddField(
            model_name='factiondivision',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='division_memberships', to='characters.character'),
        ),
    ]
