# Generated by Django 6.0 on 2026-03-16 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_alter_character_faction'),
        ('factions', '0005_factiondivision_is_public_factiondivision_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Clave única (e.g., 'mtf', 'research')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Nombre a mostrar', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#aa2222', help_text='Color hex', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icono (nombre de archivo)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de Facción',
                'verbose_name_plural': 'Tipos de Facción',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='factioninvitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faction_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factioninvitation',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faction_invitations', to='characters.character'),
        ),
    ]
