# Generated by Django 6.0 on 2026-03-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0006_add_faction_type_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accesscard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accesscard',
            name='name',
            field=models.CharField(default='Nueva Tarjeta', max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_view_l1',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_view_l2',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_view_l3',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_view_l4',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_view_l5',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_view_l6',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='level',
        ),
    ]
