# Generated by Django 6.0 on 2026-03-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0007_simplify_access_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscard',
            name='can_view_l1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accesscard',
            name='can_view_l2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accesscard',
            name='can_view_l3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accesscard',
            name='can_view_l4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accesscard',
            name='can_view_l5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accesscard',
            name='can_view_l6',
            field=models.BooleanField(default=False),
        ),
    ]
