# Generated by Django 6.0 on 2026-03-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0008_accesscard_can_view_l1_accesscard_can_view_l2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscard',
            name='can_edit_any',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_edit_o5',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_edit_scd',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_edit_scp',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_view_l1',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_view_l2',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_view_l3',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_view_l4',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_view_l5',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='can_view_l6',
        ),
    ]
