# Generated by Django 6.0 on 2026-03-16 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0009_remove_accesscard_can_edit_any_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='default_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_faction', to='factions.factionrank'),
        ),
    ]
