# Generated by Django 6.0 on 2026-08-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0010_faction_default_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscard',
            name='card_type',
            field=models.CharField(choices=[('standard', 'Estándar'), ('scientific', 'Scientific Department'), ('ethics_committee', 'Comité de Ética'), ('o5_council', 'Consejo O5'), ('raisa', 'RAISA'), ('admin_office', 'Administrators Office'), ('beta_1', 'Beta-1')], default='standard', help_text='Casos especiales (O5, RAISA, Beta-1, Comité de Ética...)', max_length=20),
        ),
        migrations.AddField(
            model_name='accesscard',
            name='level',
            field=models.CharField(choices=[('L1', 'Nivel 1'), ('L2', 'Nivel 2'), ('L3', 'Nivel 3'), ('L4', 'Nivel 4'), ('L5', 'Nivel 5'), ('L6', 'Nivel 6')], default='L1', help_text='Nivel de acceso L1-L6', max_length=4),
        ),
    ]
