# Generated by Django 6.0 on 2026-08-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0011_accesscard_card_type_accesscard_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='facade_name',
            field=models.CharField(blank=True, help_text='Nombre visible en lugar del real', max_length=100),
        ),
    ]
